spring:
  application:
    name: 'verification-service'

verification:
  check:
    timeout: 5s
    enabled:
      - VELOCITY
      - SANCTIONS
      - FRAUD
    velocity:
      window: 1m
      limit: 10
